export const AllTexts = {
  UpNext: 'Up Next',
  Complete: 'Session Complete',
  WaitingForNextSet: 'Waiting for next set',
  Playlist: 'Playlist',
  PreviousSessions: 'Previous Sessions',
  Recording: 'Recordings',
  LearnLangauageNaturalWay: 'Learn language the natural way.',
  ItalianEdition: 'Italian Edition',
  SignInWithFacebook: 'Sign in with Facebook',
  SignIn: 'Sign in',
  CreateAccount: 'Create Account',
  InvitaionToJoinAudia: 'Did you receive an invitaion to join Audia with a redeem code.',
  PleasePutRedeemCodeInBoxBelow: 'Please put your redeem code in the box below',
  PleaseSendRedeemCodeHere: 'Please send redeem code here',
  LostRedeemCode: 'lost your redeem code?',
  SelectNaturalLanguage: 'Select your natural language',
  PleaseSelectFromListBelow: 'Please select from the list below',
  English: 'English',
  SelectLanguageToLearn: 'Select a language to learn',
  YouWillChargedAfterSignUp: 'You will be charged after signing-up',
  ChooseNativeSpeaker: 'Choose male or female native speaker',
  ChooseNumberOfPhrases: 'Choose the number of phrases you want to\n practice in each session',
  SendLinkForPasswordRecovery: 'We will send a link to your registered\n email for password recovery.',
  SeemsYouNotConnectedInternet: 'Seems you are not connected to the internet.',
  SomthingWentWrong: 'Somthing went wrong please try again.',
  Error: 'Error!',
  Retry: 'Retry',
  Oops: 'Oops!',
  NoConnection: 'No Connection',
  YouCurrentlyOffline: 'You are currently offline',
  PlaylistNullTitle: 'Save and review up to',
  PlaylistNullSubTitle: 'During a set tap the icon below\n to add to playlist',
  PrivacyPolicyTitle: 'Privacy Policy',
  PrivacyPolicySubTitle: 'Lorem ipsum dolor sit amet, an his duis regione adversarium, mei in assum ubique voluptatum. Ex per nominati quaestio.',
  TermsConditionTitle: 'Terms of Use',
  TermsConditionSubTitle: 'Lorem ipsum dolor sit amet, an his duis regione adversarium, mei in assum ubique voluptatum. Ex per nominati quaestio.',
  SettingScreenAccountInfo: 'Account Info',
  SettingScreenActiveDevice: 'Active Device',
  ArchiveNullSubTitle: "You haven't added any sound bite(s) in Archive.",
  SelectUser: 'Select User',
  AddNewUser: 'Add New User',
  FirstName: 'First Name',
  LastName: 'Last Name',
  Email: 'E-mail',
  Password: 'Password',
  CurrentPassword: 'Current Password',
  AddUser: 'Add User',
  Cancel: 'Cancel',
  TakePhoto: 'Take a Photo',
  TakeFromGallery: 'Take From Gallery',
  ChooseFromLibrary: 'Choose from Library',
  PleaseEnterEmailAddress: 'Please enter email address',
  EnterCurrentPassword: 'Please enter current password',
  EnterNewPassword: 'Please enter new password',
  EnterConfirmPassword: 'Please enter confirm password',
  NotMatchConfirmPassword: 'Confirm password doesn\'t match',
  FirstNameAtLeastTwoCharacter: 'First name at least 2 characters long',
  LastNameAtLeastTwoCharacter: 'Last name at least 2 characters long',
  PleaseEnterValidEmailAddress: 'Please enter a valid email address',
  PleaseEnterValidPassword: 'Your password must be at least 8 characters long, contain one number, one special character and have a mixture of uppercase and lowercase letters',
  Archive: 'Archive',
  Play: 'Play',
  Next: 'Next',
  And: 'and',
  InAppPurchase: 'in-app purchase',
  BySigningUpYouAgreeToOur: 'By signing up, you agree to our',
  TermsAndConditions: 'Terms and Conditions',
  PrivacyPolicy: 'Privacy Policy',
  AlreadyHaveAnAccount: 'Already have an account?',
  PleaseEnterPassword: 'Please enter password',
  Downloading: 'Downloading',
  WeRecommendConnectingToWifi: 'We recommend connecting to wifi',
  ForgotPassword: 'Forgot Password',
  EnterEmail: 'enter email',
  Send: 'Send',
  Login: 'Login',
  SignUp: 'Sign up',
  Male: 'Male',
  Female: 'Female',
  Users: 'Users',
  GotIt: 'Got it!',
  IAgree: 'I Agree',
  RedeemCode: 'Redeem Code',
  Settings: 'Settings',
  LastActivity: 'Last activity',
  ActiveAccount: 'Active Account',
  ConfirmPassword: 'Confirm Password',
  Version: 'Version',
  LetsGetStarted: "Let's get started",
  HowAudiaDifferent: 'How is Audia different',
  ForgotYourPassword: 'Forgot your password',
  DontHaveAnAccount: "Don't have an account",
  ConnectWithFacebook: 'Connect with Facebook',
  PreviousSessions: 'Previous Sessions',
  ConfirmPreferences: 'Confirm Preferences',
  RulesAlertViewHeadingText: "If you're in a noisy environment, we suggest you use headphones for optimal",
  RulesAlertViewDescription: "We recommend you become immersed in the audia experience for the best results.",
  UserType: 'User Type',
  Yes: 'Yes',
  No: 'No',
  VerbSessions: 'Verb Sessions',
  TakeYourPhotoOrChooseFromLibrary: 'Take your photo or choose from library',
  NativeLanguage: 'Native Language',
  NativeSwitch: 'Native Switch',
  NextSet: 'Next Set',
  Waiting: 'Waiting',
  SwitchProfile: 'Switch Profile',
  SwitchLanguage: 'Switch language',
  SetReminder: ' Set Reminder',
  Loading: 'Loading...',
  SampleOne: 'Sample 1',
  SampleTwo: 'Sample 2',
  SavePreferences: 'Save Preferences',
  SoundLoopsPerSession: 'Sound loops per session',
  NativeSpeakerPreference: 'Native speaker preference',
  LogoutText: 'Logout',
  CreatePlayList: 'Create Playlist',
  AccessVerbSessionTitle: 'You now have access to verb sessions!',
  AccessVerbSessionSubTitle: 'Remember to complete your verb session before moving forward.',
  Continue: 'Continue',
  ChangePassword: 'Change Password',
  Submit: 'Submit',

  Play1Time: 'Play 1 time',
  Play3Times: 'Play 3 times',
  Play5Times: 'Play 5 times',
  Play10Times: 'Play 10 times',
  ContinuousPlay: 'Continuous Play',
  ThePauseRulesRestartSet: 'Oops... you waited too long,  we will restart this set',
  ThePauseRulesSuggest: 'We suggest you start over',
  TimeElapse18HRS: 'Oops... press to restart',
  AbsenceRulesAlert: 'In order to produce the best results, we suggest you repeat the previous session before advancing.',
  ButtonOverride: 'Override',
  ButtonContinue: 'Continue',
  ButtonAccept: 'Accept'

};

export const Images = {
  BtnBack: require('../../../../assets/images/btnBack.png'),
  BtnBackWhite: require('../../../../assets/images/btnBackWhite.png'),
  BtnCancel: require('../../../../assets/images/btnCancel.png'),
  HeaderLogo: require('../../../../assets/images/headerLogo.png'),
  ItalianFlag: require('../../../../assets/images/ItalianFlag.png'),
  PlusLanguageIcon: require('../../../../assets/images/plusLanguageIcon.png'),
  ArrowRight: require('../../../../assets/images/arrowRight.png'),
  ArrowRightCron: require('../../../../assets/images/arrowRightcron.png'),
  CloudData: require('../../../../assets/images/cloudData.png'),
  DataDownload: require('../../../../assets/images/dataDownload.png'),
  WiFi: require('../../../../assets/images/WiFi.png'),
  Warning: require('../../../../assets/images/warning.png'),
  DoneIcon: require('../../../../assets/images/doneIcon.png'),
  Lion: require('../../../../assets/video/lion.mp4'),
  PlayAudio: require('../../../../assets/images/playAudio.png'),
  DetailIcon: require('../../../../assets/images/detailIcon.png'),
  ToggleIcon: require('../../../../assets/images/toggleIcon.png'),
  PlaylistAdd: require('../../../../assets/images/playlistAdd.png'),
  Playlistbottom: require('../../../../assets/images/playlistbottom.png'),
  ManIconSelected: require('../../../../assets/images/manIconSelected.png'),
  ManIcon: require('../../../../assets/images/manIcon.png'),
  WomanIconSelected: require('../../../../assets/images/womanIconSelected.png'),
  WomanIcon: require('../../../../assets/images/womanIcon.png'),
  Headphone: require('../../../../assets/images/headphone.png'),
  DownArrow: require('../../../../assets/images/downArrow.png'),
  CheckboxActive: require('../../../../assets/images/checkboxActive.png'),
  CheckboxUnActive: require('../../../../assets/images/checkboxUnActive.png'),
  SessionPlay: require('../../../../assets/images/sessionPlay.png'),
  Nointernet: require('../../../../assets/images/nointernet.png'),
  UserDefaultPic: require('../../../../assets/images/userDefaultPic.png'),
  UserCount: require('../../../../assets/images/userCount.png'),
  UserPlaceholder: require('../../../../assets/images/userPlaceholder.png'),
  CancelUser: require('../../../../assets/images/cancelUser.png'),
  StarIcon: require('../../../../assets/images/starIcon.png'),
  WaitingIcon: require('../../../../assets/images/waitingIcon.png'),
  Waiting: require('../../../../assets/images/waiting.png'),
  PreviousIcon: require('../../../../assets/images/previousIcon.png'),
  PlaylistIcon: require('../../../../assets/images/playlistIcon.png'),
  MicrophoneIcon: require('../../../../assets/images/microphoneIcon.png'),
  Shape: require('../../../../assets/images/Shape.png'),
  FrenchFlag: require('../../../../assets/images/FrenchFlag.png'),
  SpanishFlag: require('../../../../assets/images/SpanishFlag.png'),
  RightTriangle: require('../../../../assets/images/rightTriangle.png'),
  DownArrow: require('../../../../assets/images/downArrow.png'),
  DefaultPicker: require('../../../../assets/images/defaultPicker.png'),
  UserCircle: require('../../../../assets/images/userCircle.png'),
  PauseAudio: require('../../../../assets/images/pauseAudio.png'),
  PlayAudio: require('../../../../assets/images/playAudio.png'),
  PlusIcon: require('../../../../assets/images/plusIcon.png'),
  TouchHand: require('../../../../assets/images/touchHand.png'),
  NextSetIcon: require('../../../../assets/images/nextSetIcon.png'),
  RepeatIcon: require('../../../../assets/images/repeatIcon.png'),
  VerbIcon: require('../../../../assets/images/verbIcon.png'),
  SettingIcon: require('../../../../assets/images/settingIcon.png'),
  FBIcon: require('../../../../assets/images/FBIcon.png'),
  ManGray: require('../../../../assets/images/manGray.png'),
  WomanGray: require('../../../../assets/images/womanGray.png'),
  RecordingDot: require('../../../../assets/images/recordingDot.png'),
  EnglishFlag: require('../../../../assets/images/EnglishFlag.png'),
  RecordingRepeatIcon: require('../../../../assets/images/recordingRepeatIcon.png'),
  SettingVideoIcon: require('../../../../assets/images/settingVideoIcon.png'),
  ZoomIcon: require('../../../../assets/images/zoomIcon.png'),
  BottomVignette: require('../../../../assets/images/bottom-vignette.png'),
  Play: require('../../../../assets/images/play.png'),
  Pause: require('../../../../assets/images/pause.png'),
  ErrorIcon: require('../../../../assets/images/error-icon.png'),
  Pause: require('../../../../assets/images/pause.png'),
  AddUserPlusIcon: require('../../../../assets/images/addUserPlusIcon.png'),
  shapepupBG: require('../../../../assets/images/shapepupupBG.png'),
  clockIcon: require('../../../../assets/images/clock.png'),
}

export const colors = {
  _FFFFFF: '#FFFFFF',
  _FF687E: '#FF687E',
  _526F99: '#526F99',
  _ededed: '#ededed',
  _012c6a: '#012c6a',
  _A9A9A9: '#A9A9A9',
  _496A9D: '#496A9D',
  _C1C1C1: '#C1C1C1',
  _8C8C8C: '#8C8C8C',
  _4299FF: '#4299FF',
  _516C94: '#516C94',
  _5C789F: '#5C789F',
  _C6C073: '#C6C073',
  _1A9E8A: '#1A9E8A',
  _113B76: '#113B76',
  _00BB71: '#00BB71',
  _8095B4: '#8095B4',
  _3190FF: '#3190FF',
  _191948: '#191948',
  _EFF6FF: '#EFF6FF',
  _000000: '#000000',
  _637DA3: '#637DA3',
  _0C0C0C: '#0C0C0C',
  _7F94B1: '#7F94B1',
  _5C6D88: '#5C6D88',
  _F6F6F6: '#F6F6F6',
  _F2F3F4: '#F2F3F4',
  _A6A6A6: '#A6A6A6',
  _383838: '#383838',
  _9A9A9A: '#9A9A9A',
  _284C80: '#284C80',
  _5B6C84: '#5B6C84',
  _5FD4A6: '#5FD4A6',
  _A5E6ED: '#A5E6ED',
  _19C0D1: '#19C0D1',
  _7E59B5: '#7E59B5',
  _4C13A0: '#4C13A0',
  _855FBD: '#855FBD',
  _9CE4C7: '#9CE4C7',
  _10A96C: '#10A96C',
  _DCDCDC: '#DCDCDC',
  _EFEFEF: '#EFEFEF',
  _C4C5C6: '#C4C5C6',
  _13BD71: '#13BD71',
  _4A90E2: '#4A90E2',
  _01BB72: '#01BB72',
  _FFED73: '#FFED73',
  _F9F9F9: '#F9F9F9',
  _E71D36: '#E71D36',
  _4A4A4A: '#4A4A4A',
  _0093FF: '#0093FF',
  _9B9B9B: '#9B9B9B',
  _BFC3C5: '#BFC3C5',
  _EF536A: '#EF536A',
  _677FA1: '#677FA1',
  _7B7B7B: '#7B7B7B',
  _a8a8a8: '#a8a8a8',
  _8d8d8d: '#8d8d8d',
  _E6E6E6: '#E6E6E6',
  _0CBE78: '#0CBE78',
  _BDBDBD: '#BDBDBD',
  _00586C: '#00586C',
  _4E6C97: '#4E6C97',
};

export const Fonts = {

};
